### ISSUE TITLE
Ionic Android 

### ISSUE THREAD

**Issue by Tanner4** [teanders58/netprof#1]
Problem with playback: it should not start playing again until file already playing finishes first.

**Comment by pavitar90** [comment]
Unable to run app on android with latest ionic 4
below is the error recieved:


BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Exception in thread "main" java.lang.NullPointerException
        at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:38)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:26)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:62)
cmd: Command failed with exit code 1 Error output:
Exception in thread "main" java.lang.NullPointerException
        at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:38)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:26)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:62)
Picked up _JAVA_OPTIONS: -Xmx512M
